import { CheckCircle2, ClipboardCheck, FileKey2, FolderSearch, Lock, Play, Server, ShieldCheck } from 'lucide-react'

const endpoints = [
  { name: 'ws-fin-07', os: 'Windows 11 · Finance', lastSeen: '32 sec ago', health: 'Healthy', trust: 'Verified' },
  { name: 'srv-app-02', os: 'Ubuntu 24.04 · App tier', lastSeen: '48 sec ago', health: 'Healthy', trust: 'Verified' },
  { name: 'dc-east-01', os: 'Windows Server · Identity', lastSeen: '1 min ago', health: 'Healthy', trust: 'Verified' },
  { name: 'ws-ops-12', os: 'Windows 11 · Operations', lastSeen: '2 min ago', health: 'Review', trust: 'Verified' },
]

export default function Velociraptor() {
  return <main className="page-shell subpage-shell">
    <section className="page-heading compact-heading"><div><p className="eyebrow"><FolderSearch size={13} /> Endpoint forensics <span className="slash">/</span> approved collections</p><h1>Velociraptor <em>evidence.</em></h1><p className="lede">Collect bounded, read-only context with provenance attached to every artifact.</p></div><div className="heading-actions"><span className="connection-badge"><i /> API reachable</span><button className="button primary"><Play size={14} /> New collection</button></div></section>
    <section className="forensics-overview"><div className="panel forensics-hero"><div className="forensics-icon"><FolderSearch size={24} /></div><div><p className="eyebrow">Collection posture</p><h2>Evidence chain intact</h2><p>4 endpoints are reporting. No collection is currently running. Every result is hashed and linked to an alert or case.</p></div><div className="hero-check"><CheckCircle2 size={18} /><span>Verified<br /><b>100%</b></span></div></div><div className="panel quick-fact"><Lock size={16} /><span><strong>Read-only mode</strong><small>VQL is not executed from free text.</small></span></div></section>
    <section className="panel table-panel"><div className="table-heading"><div><p className="eyebrow">Endpoint inventory</p><h2>Collection targets</h2></div><span className="table-meta"><Server size={14} /> {endpoints.length} enrolled</span></div><div className="endpoint-list">{endpoints.map((endpoint) => <div className="endpoint-row" key={endpoint.name}><span className="endpoint-icon"><Server size={17} /></span><div className="endpoint-name"><strong>{endpoint.name}</strong><small>{endpoint.os}</small></div><div><small className="field-label">Last seen</small><span>{endpoint.lastSeen}</span></div><div><small className="field-label">Health</small><span className={endpoint.health === 'Healthy' ? 'health-good' : 'health-review'}><i />{endpoint.health}</span></div><div><small className="field-label">Identity</small><span className="verified"><ShieldCheck size={14} /> {endpoint.trust}</span></div><button className="icon-button" aria-label={`Review ${endpoint.name}`}><ClipboardCheck size={16} /></button></div>)}</div><div className="panel-footer"><span>Collection limits: 30s runtime · 10 MB result cap · 1 endpoint scope</span><button className="text-button">View evidence vault <FileKey2 size={14} /></button></div></section>
    <section className="collection-steps"><div className="step complete"><span>01</span><div><strong>Signal selected</strong><small>Wazuh alert or investigation case</small></div></div><div className="step-line" /><div className="step active"><span>02</span><div><strong>Read-only collection</strong><small>Approved artifact with bounded scope</small></div></div><div className="step-line" /><div className="step"><span>03</span><div><strong>Analyst decision</strong><small>Evidence reviewed before response</small></div></div></section>
  </main>
}
